= SBuild Source Scheme Plugin
:pluginversion: 0.0.9000
:sbuildversion: 0.7.2.9000
:toc:
:toc-placement: preamble
:toclevels: 1

This http://sbuild.tototec.de[SBuild] Plugin provides an extensible scheme handler to provide source jars for arbitrary dependencies.

== Download

The SBuild Source Scheme Plugin can be downloaded from http://repo1.maven.org/maven2/org/sbuild/org.sbuild.plugins.sourcescheme/[Maven Central].

To include it in you SBuild buildfile use the `@classpath` annotation:

[source,scala]
[subs="attributes"]
----
@classpath("mvn:org.sbuild:org.sbuild.plugins.sourcescheme:{pluginversion}")
----

== Building from Source

You need a recent version of SBuild.

----
git clone https://github.com/SBuild-org/sbuild-sourcescheme-plugin.git
cd sbuild-sbuild-plugin/org.sbuild.plugins.sourcescheme
sbuild all
----

You will find the built jar in the directory `org.sbuild.plugins.sourcescheme/target`.

== Requirements

This plugin requires at least SBuild {sbuildversion}.

== Configuration

All configurable properties are documented via ScalaDoc. See file link:org.sbuild.plugins.sourcescheme/src/main/scala/org/sbuild/plugins/sourcescheme/SourceScheme.scala[`SourceScheme.scala`].

== Changelog

=== SBuild Source Scheme Plugin 0.1.0 - _Not Released yet_

* Initial Release.
